"""Static analysis warnings for the PC monitoring rule language."""

from __future__ import annotations

from collections import defaultdict

# El analizador trabaja sobre el AST y no necesita volver a tokenizar ni parsear.
from ast_nodes import Action, Condition, Program, Rule


# Revisa propiedades del programa que pueden ser utiles despues de ejecutarlo.
class StaticAnalyzer:
    """Revisa el programa para encontrar advertencias utiles.

    No ejecuta reglas. Solo mira el AST y, si recibe la lista de reglas que si
    se aplicaron, puede detectar cuales nunca se activaron.
    """

    def __init__(
        self,
        program: Program,
        applied_rules: set[str] | None = None,
    ) -> None:
        """Prepara el analizador con el programa y las reglas aplicadas.

        ``program`` es el AST completo. ``applied_rules`` viene del interprete y
        contiene los nombres de las reglas que llegaron a cumplirse.
        """

        # Guarda el AST y una copia del conjunto de reglas disparadas por el
        # interprete para poder detectar reglas que nunca se aplicaron.
        self.program = program
        self.applied_rules = set(applied_rules or set())

    def find_action_conflicts(self) -> list[str]:
        """Busca hechos generados por varias reglas distintas.

        Si dos reglas producen el mismo hecho pero tienen condiciones distintas,
        se reporta como posible conflicto. Si son exactamente iguales, se deja
        para el detector de redundancias.
        """

        # Agrupa reglas por el hecho que producen; un mismo hecho con reglas
        # distintas puede representar conflicto de accion.
        rules_by_fact: defaultdict[str, list[Rule]] = defaultdict(list)

        for rule in self.program.rules:
            rules_by_fact[rule.action.fact].append(rule)

        messages: list[str] = []
        for fact, rules in rules_by_fact.items():
            # Distingue conflictos reales de reglas duplicadas: si condicion y
            # accion son iguales, se reportan como redundancia, no conflicto.
            unique_condition_actions = {(rule.condition, rule.action) for rule in rules}

            if len(unique_condition_actions) > 1:
                rule_names = ", ".join(rule.name for rule in rules)
                messages.append(f"Action {fact} generated by {rule_names}")

        return messages

    def find_redundant_rules(self) -> list[str]:
        """Busca reglas que hacen exactamente lo mismo.

        Dos reglas son redundantes si tienen la misma condicion y tambien la
        misma accion, aunque tengan nombres diferentes.
        """

        # Agrupa por comportamiento observable: misma condicion y misma accion.
        rules_by_behavior: defaultdict[tuple[Condition, Action], list[Rule]] = (
            defaultdict(list)
        )

        for rule in self.program.rules:
            rules_by_behavior[(rule.condition, rule.action)].append(rule)

        messages: list[str] = []
        for rules in rules_by_behavior.values():
            # Si dos o mas reglas tienen el mismo comportamiento, son redundantes.
            if len(rules) > 1:
                rule_names = ", ".join(rule.name for rule in rules)
                messages.append(f"Redundant rules: {rule_names}")

        return messages

    def find_inactive_rules(self) -> list[str]:
        """Busca reglas que nunca se aplicaron durante la ejecucion.

        En este proyecto se reporta solo la ultima regla inactiva para coincidir
        con el formato de salida esperado.
        """

        # Compara todas las reglas del programa contra las que registro el
        # interprete como aplicadas.
        inactive_rules = [
            rule
            for rule in self.program.rules
            if rule.name not in self.applied_rules
        ]

        # Por contrato de salida de este proyecto solo se reporta la ultima
        # regla inactiva encontrada.
        if inactive_rules:
            return [f"Potentially inactive rule: {inactive_rules[-1].name}"]

        return []

    def analyze(
        self,
        include_conflicts: bool = True,
        include_redundancies: bool = True,
        include_inactive: bool = True,
    ) -> list[str]:
        """Ejecuta los analisis pedidos y devuelve todos los mensajes.

        Los parametros permiten prender o apagar conflictos, redundancias e
        inactividad. El orden de los mensajes se mantiene estable.
        """

        # Acumula mensajes en un orden estable para que las pruebas puedan
        # comparar stdout literalmente.
        messages: list[str] = []

        if include_conflicts:
            messages.extend(self.find_action_conflicts())

        if include_redundancies:
            messages.extend(self.find_redundant_rules())

        if include_inactive:
            messages.extend(self.find_inactive_rules())

        return messages
