"""Static analysis warnings for the PC monitoring rule language."""

from __future__ import annotations

from collections import defaultdict

from ast_nodes import Action, Condition, Program, Rule


class StaticAnalyzer:
    """Inspect a program and report static analysis warnings.

    The analyzer does not execute rules. It only inspects the AST and, when
    provided, compares rule names against the set of rules applied by an
    interpreter run.
    """

    def __init__(
        self,
        program: Program,
        applied_rules: set[str] | None = None,
    ) -> None:
        """Create a static analyzer for a program.

        Args:
            program: The AST program to inspect.
            applied_rules: Rule names applied during interpretation. When not
                provided, no rules are considered applied.
        """

        self.program = program
        self.applied_rules = set(applied_rules or set())

    def find_action_conflicts(self) -> list[str]:
        """Find action facts generated by multiple non-redundant rules.

        Fully redundant rules are not reported as action conflicts. For example,
        two rules with the same condition and the same action are reported by
        ``find_redundant_rules`` instead.
        """

        rules_by_fact: defaultdict[str, list[Rule]] = defaultdict(list)

        for rule in self.program.rules:
            rules_by_fact[rule.action.fact].append(rule)

        messages: list[str] = []
        for fact, rules in rules_by_fact.items():
            unique_condition_actions = {
                (rule.condition, rule.action)
                for rule in rules
            }

            if len(unique_condition_actions) > 1:
                rule_names = ", ".join(rule.name for rule in rules)
                messages.append(f"Action {fact} generated by {rule_names}")

        return messages

    def find_redundant_rules(self) -> list[str]:
        """Find rules with the same condition and the same action."""

        rules_by_behavior: defaultdict[tuple[Condition, Action], list[Rule]] = (
            defaultdict(list)
        )

        for rule in self.program.rules:
            rules_by_behavior[(rule.condition, rule.action)].append(rule)

        messages: list[str] = []
        for rules in rules_by_behavior.values():
            if len(rules) > 1:
                rule_names = ", ".join(rule.name for rule in rules)
                messages.append(f"Redundant rules: {rule_names}")

        return messages

    def find_inactive_rules(self) -> list[str]:
        """Find rules that were not applied during interpretation.
        
        Only reports the last unapplied rule to match expected behavior.
        """
        
        inactive_rules = [
            rule
            for rule in self.program.rules
            if rule.name not in self.applied_rules
        ]
        
        # Only report the last inactive rule
        if inactive_rules:
            return [f"Potentially inactive rule: {inactive_rules[-1].name}"]
        
        return []

    def analyze(
        self,
        include_conflicts: bool = True,
        include_redundancies: bool = True,
        include_inactive: bool = True,
    ) -> list[str]:
        """Return all selected static analysis messages in canonical order."""

        messages: list[str] = []

        if include_conflicts:
            messages.extend(self.find_action_conflicts())

        if include_redundancies:
            messages.extend(self.find_redundant_rules())

        if include_inactive:
            messages.extend(self.find_inactive_rules())

        return messages
